spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    debug: true
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: test-client
            client-secret: meye2YQkC7qbjVQfd8H1j9LAxpKfQdkF
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            client-name: test-client
            client-authentication-method: client_secret_basic
            scope: openid,email
        provider:
          keycloak:
            issuerUri: http://localhost:8081/realms/oidc-test
            user-name-attribute: preferred_username

logging:
  level:
    web: debug
    security: debug


